#define TENO_ERROR -1

#define MEMORY_ALLOCATE_FAILED -2;

#define MYSQL_INIT_FAILED -3
#define MYSQL_CONNECT_FAILED -4
#define EXECUTE_SQL_FAILED -5
#define MYSQL_STORE_FAILED -6

#define TASK_ID_ERROR -10